server:
  port: 9000
spring:
  main:
    web-application-type: reactive
  data:
    redis:
#      host: localhost
      host: { redis地址 }
      port: { redis端口 }
      password: { redis密码 }
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: { nacos地址 }:{ nacos端口 }
        username: { nacos用户名 }
        password: { nacos密码 }
        ephemeral: false
    gateway:
      globalcors:
        # 解决浏览器向服务器发options请求被拦截问题，这样网关就不拦截这个请求了
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          # 拦截所有请求
          '[/**]':
            allowedOrigins:
              - "http://localhost:3200"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: blog
          uri: lb://ahzoo-z2blog
          predicates:
            - Path=/blog/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver:  "#{@allRequest}"
                # 令牌桶的填充率（每秒填充多少个令牌）
                redis-rate-limiter.replenishRate: 1000
                # 令牌桶最大数量
                redis-rate-limiter.burstCapacity: 5000
        - id: search
          uri: lb://ahzoo-search
          predicates:
            - Path=/search/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@allRequest}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000
        - id: comment
          uri: lb://ahzoo-comment
          predicates:
            - Path=/comment/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@allRequest}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000
        - id: admin
          uri: lb://ahzoo-blog-admin
          predicates:
            - Path=/admin/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@allRequest}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000
